--mysql
drop table if exists tb_<%= key %>;

create table tb_<%= key %> (
    id bigint auto_increment,	<%
		value.each do |k,v|
		propName = k
		propType = v.split(',')[0]
		if 'String' == propType
		  sqlPropType = 'varchar(255)'
		elsif 'double' == propType
		  sqlPropType = 'double(4,10)'
		elsif 'Date' == propType
		  sqlPropType = 'timestamp'
		elsif 'int' == propType
		  sqlPropType = 'int(11)'
		else
		  sqlPropType = 'bigint '
		end
		propDesc = v.split(',')[1]	%>
    `<%= propName %>` <%= sqlPropType %> null,<% end %>
    primary key (id)
) engine=InnoDB;

--h2

drop table if exists tb_<%= key %>;

create table tb_<%= key %> (
    id bigint generated by default as identity, <%
                value.each do |k,v|
                propName = k
                propType = v.split(',')[0]
                if 'String' == propType
                  sqlPropType = 'varchar(255)'
                elsif 'double' == propType
                  sqlPropType = 'double(4,10)'
                elsif 'Date' == propType
                  sqlPropType = 'timestamp'
                elsif 'int' == propType
                  sqlPropType = 'int(11)'
                else
                  sqlPropType = 'bigint '
                end
                propDesc = v.split(',')[1]      %>
    `<%= propName %>` <%= sqlPropType %> null,<% end %>
    primary key (id)
);
